version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    volumes:
    - ./:/app
    - ./.docker/local.ini:/usr/local/etc/php/conf.d/local.ini